version: '3.8'

services:
  api:
    build:
      context: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
    container_name: finetuned-model-api
